name: Uptime (Master)
on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write
  pages: write
  id-token: write

concurrency:
  group: upptime-pages
  cancel-in-progress: false

jobs:
  uptime:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1) Uptime checks (opens/closes issues, updates history)
      - name: Upptime update
        uses: upptime/uptime-monitor@v1.41.0
        with:
          command: "update"
        env:
          GH_PAT: ${{ secrets.GH_PAT || github.token }}
          SECRETS_CONTEXT: ${{ toJson(secrets) }}

      # 2) Record response times (feeds graphs)
      - name: Upptime response-time
        uses: upptime/uptime-monitor@v1.41.0
        with:
          command: "response-time"
        env:
          GH_PAT: ${{ secrets.GH_PAT || github.token }}

      # 3) Generate summary JSON consumed by the site
      - name: Upptime summary
        uses: upptime/uptime-monitor@v1.41.0
        with:
          command: "summary"
        env:
          GH_PAT: ${{ secrets.GH_PAT || github.token }}

      # 4) Generate graphs
      - name: Upptime graphs
        uses: upptime/uptime-monitor@v1.41.0
        with:
          command: "graphs"
        env:
          GH_PAT: ${{ secrets.GH_PAT || github.token }}

      # 5) Build static site (outputs to ./site/status-page/__sapper__/export)
      - name: Upptime site build
        uses: upptime/uptime-monitor@v1.41.0
        with:
          command: "site"
        env:
          GH_PAT: ${{ secrets.GH_PAT || github.token }}

      # (Optional) Show what was built so issues are obvious in logs
      - name: List site output
        run: |
          echo "== export root =="
          ls -lah site/status-page/__sapper__/export || true
          echo "== expect to see: index.html, CNAME, api/, assets/ =="
          ls -lah site/status-page/__sapper__/export/api 2>/dev/null || true

      # 6) Configure and deploy GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/status-page/__sapper__/export

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
