name: Uptime (Core)
on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes
  workflow_dispatch:

jobs:
  uptime:
    runs-on: ubuntu-latest
    concurrency:
      group: upptime
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT || github.token }}

      # Use the subset config so Experian is NOT polled here
      - name: Use core config (subset, NO Experian)
        run: cp .upptimerc-core.yml .upptimerc.yml

      # Run checks & update history/incidents (NO site build here)
      - name: Check endpoint status
        uses: upptime/uptime-monitor@v1.37.0
        with:
          command: "update"
        env:
          GH_PAT: ${{ secrets.GH_PAT || github.token }}
          SECRETS_CONTEXT: ${{ toJson(secrets) }}