name: Uptime (Master)
on:
  schedule:
    - cron: "0 */2 * * *"   # every 2 hours
  workflow_dispatch:

jobs:
  uptime:
    runs-on: ubuntu-latest
    concurrency:
      group: upptime
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT || github.token }}

      # Ensure we use the full (master) config for this run
      - name: Use master config (full list incl. Experian)
        run: cp .upptimerc.yml .upptimerc.yml

      # 1) Run checks & update history/incidents
      - name: Check endpoint status
        uses: upptime/uptime-monitor@v1.37.0
        with:
          command: "update"
        env:
          GH_PAT: ${{ secrets.GH_PAT || github.token }}
          SECRETS_CONTEXT: ${{ toJson(secrets) }}

      # 2) Build & publish the status website (MASTER ONLY)
      - name: Build status site
        uses: upptime/uptime-monitor@v1.37.0
        with:
          command: "site"
        env:
          GH_PAT: ${{ secrets.GH_PAT || github.token }}
