name: Uptime (Master)
on:
  schedule:
    - cron: "0 */2 * * *"   # every 2 hours
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write
  pages: write
  id-token: write

concurrency:
  group: upptime-pages
  cancel-in-progress: false

jobs:
  uptime:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1) Generate data (history, summary) used by the site
      - name: Upptime update
        uses: upptime/uptime-monitor@v1.41.0
        with:
          command: "update"
        env:
          GH_PAT: ${{ secrets.GH_PAT || github.token }}
          SECRETS_CONTEXT: ${{ toJson(secrets) }}

      # 2) Build the static site into ./site/status-page/__sapper__/export
      - name: Upptime site build
        uses: upptime/uptime-monitor@v1.41.0
        with:
          command: "site"
        env:
          GH_PAT: ${{ secrets.GH_PAT || github.token }}

      # 3) DEBUG: list what was built so we know the path is right
      - name: List site root
        run: |
          echo "== site =="
          ls -lah site || true
          echo "== site/status-page =="
          ls -lah site/status-page || true
          echo "== export root =="
          ls -lah site/status-page/__sapper__/export || true
          echo "== export tree (first 200 lines) =="
          ls -R site/status-page/__sapper__/export | head -n 200 || true

      # 4) Configure Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # 5) Upload the actual static export (must contain index.html, api/, CNAME, assets/)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/status-page/__sapper__/export

      # 6) Deploy to Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
