name: Uptime (Master)
on:
  schedule:
    - cron: "0 */2 * * *"   # every 2 hours
  workflow_dispatch:

permissions:
  contents: write       # commit history files
  issues: write         # open/close incident issues
  pull-requests: write  # maintenance PRs if any
  pages: write          # deploy GitHub Pages
  id-token: write       # OIDC token for Pages

concurrency:
  group: upptime-pages
  cancel-in-progress: false

jobs:
  uptime:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1) Run checks & update history/incidents (creates data used by the site)
      - name: Check endpoint status
        uses: upptime/uptime-monitor@v1.37.0
        with:
          command: "update"
        env:
          GH_PAT: ${{ secrets.GH_PAT || github.token }}
          SECRETS_CONTEXT: ${{ toJson(secrets) }}

      # 2) Build static status site into ./site/status-page/__sapper__/export
      - name: Build status site
        uses: upptime/uptime-monitor@v1.37.0
        with:
          command: "site"
        env:
          GH_PAT: ${{ secrets.GH_PAT || github.token }}

      # 3) Configure GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # 4) Upload the generated export dir as the Pages artifact (IMPORTANT: correct path)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/status-page/__sapper__/export

      # 5) Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
